image: node:lts-alpine

stages:
 - build
 - lint
 - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  NEXT_PUBLIC_GOOGLEMAP_API_KEY: $NEXT_PUBLIC_GOOGLEMAP_API_KEY
  NEXT_PUBLIC_FIREBASE_API_KEY: $NEXT_PUBLIC_FIREBASE_API_KEY
  NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
  NEXT_PUBLIC_FEEDFACTORY_API_KEY: $NEXT_PUBLIC_FEEDFACTORY_API_KEY

cache: 
  key: ${CI_COMMIT_REF_SLUG} 
  paths: 
    - .npm/
    - src/frontend/node_modules/
    - cache/Cypress
    - cache/*

install:
  stage: build
  cache: 
    paths: 
      - .npm/
      - src/frontend/node_modules/
      - cache/*
    policy: push
  script:
    - cd src/frontend
    - npm ci --force

prettier:
  stage: lint
  cache: 
    paths: 
      - .npm/
      - node_modules/
      - cache/*
    policy: pull
  script:
    - cd src/frontend  
    - npm run prettier

eslint:
  stage: lint
  cache: 
    paths: 
      - .npm/
      - node_modules/
      - cache/Cypress
      - cache/*
    policy: pull
  script:
    - cd src/frontend
    - npm run lint

e2e-test:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: test
  cache: 
    paths: 
    - .npm/
    - node_modules/
    - cache/Cypress
    - cache/*
    policy: pull
  script: 
    - cd src/frontend
    - npm run test:e2e
  artifacts:
    paths:
      - src/frontend/coverage
    untracked: false
    expire_in: 1 days

component-test:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: test
  cache: 
    paths: 
    - .npm/
    - node_modules/
    - cache/Cypress
    - cache/*
    policy: pull
  script: 
    - cd src/frontend
    - npm run test:component
  artifacts:
    paths:
      - src/frontend/coverage
    untracked: false
    expire_in: 1 days


  