image: node:lts-alpine

stages:
 - build
 - lint
 - test

cache: 
  paths: 
    - src/frontend/node_modules/

install:
  stage: build
  script:
    - cd src/frontend
    - npm i --force
  artifacts:
    paths:
      - node_modules
    untracked: false
    expire_in: 7 days

eslint:
  stage: lint
  script:
    - cd src/frontend
    - npm run lint
    

prettier:
  stage: lint
  script:
    - cd src/frontend
    - npm run prettier

test:
  stage: test
  script: 
    - cd src/frontend
    - npm run test
