image: node

stages:
 - lint

cache: 
  paths: 
    - src/backend/node_modules/
    - src/frontend/node_modules/

eslint:
  stage: lint
  script:
    - cd src/backend/
    - npm install
    - npm run lint
    - cd ../frontend/
    - npm install
    - npm run lint
