image: node:lts-alpine

stages:
 - build
 - lint
 - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: 
  key: ${CI_COMMIT_REF_SLUG}
  paths: 
    - node_modules/
    - cache/*

install:
  stage: build
  script:
    - cd src/frontend
    - npm i --force
  artifacts:
    paths:
      - src/frontend/node_modules
    untracked: false
    expire_in: 7 days

eslint:
  stage: lint
  script:
    - cd src/frontend
    - npm run lint
    

prettier:
  stage: lint
  script:
    - cd src/frontend  
    - npm run prettier

test:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: test
  script: 
    - cd src/frontend
    - npm run test
  artifacts:
    when: always
    paths:
      - src/frontend/cypress/videos/**/*.mp4
      - src/frontend/cypress/screenshots/**/*.png
    expire_in: 1 day
