image: node:lts-alpine

stages:
 - lint

cache: 
  paths: 
    - src/backend/node_modules/
    - src/frontend/node_modules/

eslint:
  stage: lint
  script:
    - cd src/backend/
    - npm install --force
    - npm run lint
    - cd ../frontend/
    - npm install --force
    - npm run lint

prettier:
  stage: lint
  script:
    - cd src/frontend 
    - npm i --force
    - npm run prettier
