import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Wrapper, Status } from "@googlemaps/react-wrapper";
import GMap from './gmaps/gmap';

const Home: NextPage = () => {

  const [clicks, setClicks] = React.useState<google.maps.LatLng[]>([]);
  const [zoom, setZoom] = React.useState(3); // initial zoom
  const [center, setCenter] = React.useState<google.maps.LatLngLiteral>({
    lat: 10,
    lng: 10,
  });

  const render = (status: Status) => {
    return <h1>{status}</h1>;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      
      

      <main className={styles.main}>

        <Wrapper apiKey={"AIzaSyD2Zs61dN0v-Rv871JYZR6GzVy_intXtv8"} render={render}>
          <GMap center={center} zoom={zoom}></GMap>
        </Wrapper>

    
      </main>
    </div>
  )
}

export default Home
